name: Testitem CI workflow

on:
  workflow_call:
    inputs:
      include-release-versions:
        type: boolean
        required: false
        default: true
      include-lts-versions:
        type: boolean
        required: false
        default: true
      include-all-compatible-minor-versions:
        type: boolean
        required: false
        default: false
      include-smallest-compatible-minor-versions:
        type: boolean
        required: false
        default: true
      include-rc-versions:
        type: boolean
        required: false
        default: false
      include-beta-versions:
        type: boolean
        required: false
        default: false
      include-alpha-versions:
        type: boolean
        required: false
        default: false
      include-nightly-versions:
        type: boolean
        required: false
        default: false
    secrets:
      codecov_token:
        required: true

jobs:
  lint:
    runs-on: ubuntu-latest
    outputs:
      lint-results: ${{ steps.lint-step.outputs.lint-results }}
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/julia-lint@main
        id: lint-step

  compute-test-matrix:
    runs-on: ubuntu-latest
    outputs:
      test-matrix: ${{ steps.compute-test-matrix.outputs.test-matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/julia-compute-test-matrix@main
        id: compute-test-matrix
        with:
          include-release-versions: ${{ inputs.include-release-versions }}
          include-lts-versions: ${{ inputs.include-lts-versions }}
          include-all-compatible-minor-versions: ${{ inputs.include-all-compatible-minor-versions }}
          include-smallest-compatible-minor-versions: ${{ inputs.include-smallest-compatible-minor-versions }}
          include-rc-versions: ${{ inputs.include-rc-versions }}
          include-beta-versions: ${{ inputs.include-beta-versions }}
          include-alpha-versions: ${{ inputs.include-alpha-versions }}
          include-nightly-versions: ${{ inputs.include-nightly-versions }}

  run-tests:
    needs: compute-test-matrix
    strategy:
        fail-fast: false
        matrix:
          include: ${{ fromJson(needs.compute-test-matrix.outputs.test-matrix) }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: julia-actions/install-juliaup@v2
      with:
        channel:  ${{ matrix.juliaup-channel }}
    - uses: julia-actions/julia-buildpkg@v1
    - name: Run tests
      uses: julia-actions/julia-run-testitems@main
      with:
        juliaup-channel: ${{ matrix.juliaup-channel }}
        results-path: ${{ format('testitemresults-{0}-{1}.json', matrix.os, matrix.juliaup-channel) }}
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ format('testitemresults-{0}-{1}', matrix.os, matrix.juliaup-channel) }}
        path: ${{ format('testitemresults-{0}-{1}.json', matrix.os, matrix.juliaup-channel) }}
        retention-days: 1
    - uses: julia-actions/julia-processcoverage@v1
      if: always()
    - uses: codecov/codecov-action@v4
      if: always()
      with:
        files: ./lcov.info
        flags: unittests
        token: ${{ secrets.codecov_token }}

  report-results:
    needs: [run-tests, lint]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: testitemresults-*
          path: testresults
          merge-multiple: true
      - uses: julia-actions/julia-report-ci-results@main
        with:
          results-path: testresults
          lint-results: ${{ needs.lint.outputs.lint-results }}

  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-docdeploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
