name: Testitem CI workflow

on:
  workflow_call:
    secrets:
      codecov_token:
        required: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/julia-lint@main
  run-tests:
    strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: julia-actions/install-juliaup@v2
      with:
        channel: "release"
    - name: Compute channels from Project.toml bounds
      id: compute_juliaup_channels
      uses: julia-actions/julia-get-compatible-juliaup-channels@main
    - name: Install Julia versions
      run: |
        $channels = "$($env:JULIAUP_CHANNELS)" | ConvertFrom-Json -AsHashtable
        $channels | % {juliaup add $_}        
      shell: pwsh
      env:
        JULIAUP_CHANNELS: ${{ steps.compute_juliaup_channels.outputs.juliaup-channels }}
    - name: Clone registries
      run: |
        $channels = "$($env:JULIAUP_CHANNELS)" | ConvertFrom-Json -AsHashtable

        $channels | % {
          $Env:JULIA_DEPOT_PATH = "${{ runner.tool_cache }}/juliadepots/julia-$_"
          
          julia +$_ --project=. -e 'using Pkg; Pkg.Registry.add("General")'
        }
      shell: pwsh
      env:
        JULIAUP_CHANNELS: ${{ steps.compute_juliaup_channels.outputs.juliaup-channels }}
    - name: Instantiate and precompile
      id: prepare_foo
      run: |
        $channels = "$($env:JULIAUP_CHANNELS)" | ConvertFrom-Json -AsHashtable

        $channels | % {
          $Env:JULIA_DEPOT_PATH = "${{ runner.tool_cache }}/juliadepots/julia-$_"
          
          julia +$_ --project=. --code-coverage=user --startup-file=no --history-file=no --depwarn=no -e 'using Pkg; Pkg.instantiate()'
        }

        $new_channels = $channels | % { @{ Depot = "${{ runner.tool_cache }}/juliadepots/julia-$_"; Channel = $_ } } | ConvertTo-Json

        Write-Host $new_channels

        "PROFILES=$new_channels" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
      shell: pwsh
      env:
        JULIAUP_CHANNELS: ${{ steps.compute_juliaup_channels.outputs.juliaup-channels }}
    - name: Run tests
      uses: julia-actions/julia-run-testitems@main
      with:
        profiles: ${{ steps.prepare_foo.PROFILES }}
    - uses: julia-actions/julia-processcoverage@v1
      if: always()
    - uses: codecov/codecov-action@v4
      if: always()
      with:
        files: ./lcov.info
        flags: unittests
        token: ${{ secrets.codecov_token }}

  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-docdeploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
